cloud-barista/cm-beetle

scripts/system-info/README.md, scripts/system-info/system_info.py
This PR provides a System Information Extractor in a Python script.
This script, written in Python, collects various hardware and software information from the host system.
It can be useful for extracting and referencing the configuration of the source computing environment in cloud migration projects.
This script helps to quickly understand the current state of the system and diagnose issues.
It is useful for checking and referencing the configuration of the source computing environment for the cloud migrator project.
- `psutil`
- `prettytable`
- `netifaces`
- `pyyaml`
- `GPUtil`
```bash
python3 system_info.py
```
Collects OS name, version, architecture, platform, boot time, currently logged-in user, kernel version, and distribution information.
```python
def get_os_info():
"""Fetch …
```
=> Add a script to extract information from source system

.github/workflows/continuous-delivery.yaml, Dockerfile, README.md, conf/setup.env, pkg/api/rest/server/migration/migration.go, pkg/api/rest/server/migration/model.go, pkg/api/rest/server/server.go
- Describe how to run CM-Beetle
- Change the CD workflow to only run on tags due to GitHub Packages billing
- Skip BasicAuth when the host is localhost, health-check, etc.
=> Update README and related things

README.md
swag 실행 파일이 없는 경우 에러가 발생하기 때문에 간단한 설치 방법을 추가합니다.
혹시 특정 버전을 명시해야 하는 경우 알려주시면 반영하도록 하겠습니다.
=> Add how to install swag in README.md

pkg/logger/logger.go
- Share a single lumberjack.Logger instace/file point for concurrency
- Add NewLogger()
- Modify init() with the the lumberjack and NewLogger()
- Exception handling
- When an incorrect value is entered,
- a Warn message is output and the default value is applied.
<details>
<summary>Click to see test code </summary>
```go
l1 := logger.NewLogger(zerolog.ErrorLevel)
l2 := logger.NewLogger(zerolog.WarnLevel)
l3 := logger.NewLogger(zerolog.InfoLevel)
l4 := logger.NewLogger(zerolog.DebugLevel)
l5 := logger.NewLogger(zerolog.TraceLevel)
go func() {
for i := 0; i < 50; i++ {
log.Debug().Msg("[log] Debug mesaage")
log.Info().Msg("[log] Info mesaage")
log.Warn().Msg("[log] Warn mesaage")
log.Error().Msg("[log] Error mesaage")
}
}()
go func() {
for i := 0; i < 50; i++ {
l1.Debug().Msg("[l1] Debug …
```
=> Enhance logger

cmd/cm-beetle/main.go, pkg/api/rest/server/server.go, pkg/logger/logger.go
This PR will
- replace Echo logger middleware from default to Zerolog-based one
- fix lint error (ineffectual assignment to err (ineffassign)), and
- remove unused code.
=> Replace Echo logger middleware from default to Zerolog-based one

deployments/kubernetes/deployment.yaml, deployments/kubernetes/service.yaml
This PR will add manifests to deploying CM-Beetle on a Kubernetes cluster.
* Add `deployment.yaml`
* Add `service.yaml`
=> Add manifests initially

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/api/rest/common/namespace.go, pkg/api/rest/controller/migration.go, pkg/api/rest/route/namespace.go, pkg/core/common/namespace.go, pkg/core/recommendation/recommendation.go
This PR will initially provide a selection function of the most appropriate VM OS image based on Levenshtein Distance.
* Add Levenshtein Distance mechanism
* Select the keywords representing a server OS info from the source computing infra
* Calculate text similarity between keywords and VM OS image ID/Description
* Select the VM OS image that shows the highest similarity value
(see [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) - wikipedia)
**Matching server OS information and VM OS image info is difficult**. For example, there are 2 texts.
text1: "ubuntu 22.04.4 LTS (Jammy Jellyfish) x86_64 SSD" 
: It's extracted/selected one by one from the physical machine info from source computing infra
text2: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220609 …
=> Select the most appropriate VM OS image based on Levenshtein Distance

go.mod, go.sum, pkg/core/recommendation/recommendation.go, pkg/example/levenshtein-distance/main.go
* Add SequenceMatcher calculating text similarity
* Add an example to compare LevenshteinDistance and SequenceMatcher
This PR will help recommend a more ideal VM OS image.
: When a user inputs "Ubuntu 22.04.4 LTS (Jammy Jellyfish) x86_64 SSD" and requests a recommendation for a VM OS image, : among many images, "ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20191002" can be recommended as an ideal image.
It has been discovered that in some cases, **LevenshteinDistance is not properly recommending VM OS images**.
For example, when comparing '22.04' with '22.04.4', '20.04', and '18.04', '22.04.4' should be the most similar one.
But, the results were as follows.
* Comparing '22.04' with '22.04.1': The similarity ratio is 0.71
* Comparing '22.04' with '20.04': The similarity ratio is …
=> Enhance the function to find an ideal VM OS image

.github/workflows/continuous-delivery.yaml, .github/workflows/continuous-integration.yaml, pkg/api/rest/model/README.md
* Update CI and CD workflows
* Synchronize on-premise model (currently the metric of source computing infra analysis), but no models have changed.
* Test with CM-Honeybee, CB-Spider, and CB-Tumblebug
* Update the execution guide separately  (see https://github.com/cloud-barista/cm-beetle/discussions/73)
=> Staging for v0.2.0 release

pkg/core/recommendation/recommendation.go, pkg/example/strcomp/main.go, pkg/strcomp/strcomp.go
* Modularize text similarity features into `strcomp` pkg
* Predefine the known architecture information as a map because text similarity comparison is not possible.
* Improve the recommendation accuracy/performance through the combined use of map search and SequenceMatcher
I'd like to show the 2 example cases by following logs.
Case 1
- Similarity Score: 0.69
- Items found to be similar: 5 items
```
Comparing keywords with VM Image:
Keywords: 'Ubuntu 22.04.4 LTS (Jammy Jellyfish) x86_64 SSD'
VM Image: 'ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220609'
{"level":"trace","time":"2024-07-16T15:22:54+09:00","message":"From text 1: Ubuntu 22.04.4 LTS (Jammy Jellyfish) x86_64 SSD"}
{"level":"trace","time":"2024-07-16T15:22:54+09:00","message":"To word array 1: [ubuntu 22.04.4 lts …
```
=> Enhance the infra recommendation algorithm for VM OS image

pkg/example/proxy/proxy-server-regex-rewrite/main.go, pkg/example/proxy/proxy-server/main.go, pkg/example/proxy/target-server/main.go
* Add proxy-server sample
* Add proxy-server with RegexRewrite sample
* Add target-server sample
=> Add samples of proxy middleware

Makefile
- `make lint` command will fail in the new environment.
- New golangci-lint requires golang v1.23. So, use an older version, which is compatible with v1.21.
=> Makefile: Fix golangci-lint compatibility issue

Dockerfile, deployments/docker-compose/docker-compose.yaml
=> Bugfix in Dockerfile and docker-compose.yaml

Makefile
Reverts cloud-barista/cm-beetle#110
We can now revert this change to use the new linter after https://github.com/cloud-barista/cm-beetle/commit/03d77e7545b94dc4e9b85cb302d7bba9ca20d2b5.
=> Specify `golangci-lint` version supporting Go 1.23

pkg/core/migration/migration.go
Modified tumblebug's api endpoint to get it from a common variable.
The API authentication method is taken from an environment variable, but may need to be modified later.
apiUser := os.Getenv(“BEETLE_API_USERNAME”)
apiPass := os.Getenv(“BEETLE_API_PASSWORD”)
=> Infrastructure Migration API bug fix(issue #120)

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/api/rest/controller/migration.go, pkg/api/rest/controller/recommendation.go, pkg/api/rest/controller/sample.go
=> Add OperationID to API docs

api/docs.go, api/swagger.json, api/swagger.yaml, cmd/cm-beetle/main.go, go.work.sum, pkg/api/rest/common/utility.go, pkg/api/rest/middlewares/tumblebug-init-checker.go, pkg/api/rest/server.go
* Add a middleware to check if Tumblebug is initialized (temporarily)
* Bugfix `@ID` missing in API annotations
About the middleware
**Before Tumblebug is initialized**
Logs:
```
cb-tumblebug       | 11:42AM ERR src/api/rest/server/middlewares/zerologger.go:72 > request error error="code=404, message=Not valid namespace" URI=/tumblebug/ns/system/resources/image bytes_in= bytes_out=34 client_ip=172.25.0.5 id=1726746145103384911 latency_human="861.3µs" method=GET status=404
cm-beetle          | 11:42AM WRN pkg/api/rest/middlewares/tumblebug-init-checker.go:52 > Tumblebug needs to be initialized. error="[Error from: http://cb-tumblebug:1323/tumblebug/ns/system/resources/image] Status code: 404 Not Found, Message: {\"message\":\"Not valid namespace\"}\n"
cm-beetle          | 11:42AM INF …
```
=> Bugfix and update API handling

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/api/rest/controller/recommendation.go
* If `desiredProvider` and `desiredRegion` are set on the request body, the values in the query parameter will be ignored.
(Note)
This is temporarily supported for integration between subsystems.
It will be updated later.
(Example)
=> Support query param for desired provider and region

deployments/docker-compose/docker-compose.yaml, go.mod, go.sum, pkg/api/rest/controller/recommendation.go, pkg/api/rest/server.go, pkg/core/recommendation/recommendation.go
1. Implemented new functions to call Tumblebug's K8s node recommendation API:
- RecommendContainer
- RecommendContainerInfra
2. Added new API endpoint for container infrastructure recommendations in pkg/api/rest/server.go
3. Renamed existing functions for clarity:
- Recommend → RecommendVM
- RecommendInfra → RecommendVMInfra
4. Modified docker-compose.yaml to use Tumblebug version 0.10.6 instead of 0.10.3 to resolve K8s cluster creation issues
=> Add Container Infrastructure Recommendation API

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/api/rest/controller/migration-resource.go, pkg/client/tumblebug/mci.go, pkg/core/recommendation/vm-infra.go
- Add IPv6 rule detection and filtering to skip unsupported IPv6 firewall rules
- Implement CB-Spider specification compliance for protocol port handling:
* ALL protocol: use port -1 instead of port ranges
* ICMP protocol: use port -1 (no port concept for ICMP)
* TCP/UDP protocols: maintain 1-65535 port range for wildcards
- Skip default inbound/outbound ALL traffic rules to prevent conflicts with existing rules by cloud providers CB-Spider, or CB-Tumblebug
=> feat: improve security group rule generation

cmd/test-cli/testdata/recommendation-request.json, cmd/test-cli/testresult/beetle-test-results-alibaba.md, cmd/test-cli/testresult/beetle-test-results-aws.md, cmd/test-cli/testresult/beetle-test-results-azure.md, cmd/test-cli/testresult/beetle-test-results-gcp.md, cmd/test-cli/testresult/beetle-test-results-ncp.md, deployments/docker-compose/docker-compose.yaml, docs/beetle-v0.4.0-integration-and-testing-with-tumblebug-honeybee-and-model.md, pkg/core/compat/compat-aws.go
- Make NVMe driver optional for Xen AMIs on Nitro instances
- Remove hardcoded instance family lists for maintainability
- Allow Xen-on-Nitro compatibility with ENA driver support only
- Add permissive fallback for unknown driver compatibility cases
- Enable debug logging in development environment
- Testing on 5 CSPs
=> fix(aws-compat): mitigate strict AWS spec-image compatibility checks

api/docs.go, api/swagger.json, api/swagger.yaml, go.mod, go.sum, pkg/api/rest/controller/migration-data.go, pkg/api/rest/server.go
* Integrate transx library and add experimental data migration API for transferring data between remote endpoints using rsync and S3-style methods
* Support relay mode data migration with validation and error handling for remote-to-remote transfers
=> feat(experimental): Add data migration API with transx integration
